apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tacticalrmm
  labels:
    app: tacticalrmm
    service: tactical-frontend
  name: tactical-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tactical-frontend
  strategy: {}
  template:
    metadata:
      labels:
        service: tactical-frontend
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: trmm-frontend
          image: tacticalrmm/tactical-frontend:0.14.1
          resources: {}
          env:
            - name: API_HOST
              value: api.rmm.mydomain.com
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: tacticalrmm
  labels:
    app: tacticalrmm
    service: tactical-frontend
  name: tactical-frontend
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    service: tactical-frontend
